name: Action Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ghalint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run ghalint
        uses: suzuki-shunsuke/ghalint-action@v1

  pinact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run pinact
        uses: suzuki-shunsuke/pinact-action@v1
