name: Action Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ghalint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup aqua
        uses: aquaproj/aqua-installer@v4
        with:
          aqua_version: v2.43.1

      - name: Run ghalint
        run: |
          aqua install -t ghalint
          ghalint run

  pinact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run pinact
        uses: suzuki-shunsuke/pinact-action@v1
        with:
          skip_push: "true"
